### ISSUE TITLE
CAST function - unspported type boolean

### ISSUE THREAD

**Issue by samvaughton** [orocrm/doctrine-extensions#16]
I need to cast `text` to `boolean` as I am accessing JSON properties but the CAST function does not support it. Would this be something you are willing to add / accept a PR for?

edit: this is on Postgres

Cheers

**Comment by x86demon** [comment]
Hi.
Only if it is applicable for all supported platform.

**Comment by samvaughton** [comment]
MySQL does not support casting to a `boolean` using the `CAST` function - so I presume no on this?

**Comment by x86demon** [comment]
Goal of this extension is to provide same set of functionality for all supported DB Platform. If same DQL will return different result for different platform this may break application logic.
But in case of casting to boolean on MySQL `1` and `0` may be acceptable.
