### ISSUE TITLE
GROUP_CONCAT With string and not identifier

### ISSUE THREAD

**Issue by Gawel1** [orocrm/doctrine-extensions#19]
Hello,

It seems to be not possible to use your GROUP_CONCAT DQL method with simple strings args : 

For example, i want to generate JSON string with this instruction  : GROUP_CONCAT('{report:"',r.label,'", expiration_date:"', ur.expiration_date, '"}').

**Comment by x86demon** [comment]
Hi, @Gawel1 
In this case CONCAT must be used.

Group concat is equal to http://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_group-concat

**Comment by Gawel1** [comment]
The problem is there can be more than one line : 
Example :
a table with :  
a | b | c
a | d | e

I want in output : a | [{label1 : b, label2 : c},{label1 : e, label2 : e}] and group_concat works fine for do that.

**Comment by x86demon** [comment]
Please, provide your DQL

**Comment by Gawel1** [comment]
This MYSQL request give the result i want :

SELECT u.email, CONCAT(u.first_name,' ', u.last_name) AS full_name, ur.is_active AS activated_licence, CONCAT('[', GROUP_CONCAT('{report:"',r.label,'", expiration_date:"', ur.expiration_date, '"}'), ']') AS licences FROM user u left join user_report ur ON ur.user_id=u.id left join report r ON ur.report_id=r.id WHERE u.company_id=%d AND u.status =  AND u.role != %s GROUP BY u.email ORDER BY u.email;

**Comment by x86demon** [comment]
Hi, @Gawel1 
Issue was found and fixed. Thank you for patience
