### ISSUE TITLE
doctrine-extensions installation error

### ISSUE THREAD

**Issue by jbarberillo** [orocrm/doctrine-extensions#20]
Hello,
I'm using symfony 2.7.1 and I have some problems to install doctrine-extensions.
I followed the installation steps but symfony throws me that error.

Attempted to load class "Cast" from namespace "Oro\ORM\Query\AST\Functions".
Did you forget a "use" statement for another namespace? 

Here is the config.yml file: http://pastebin.com/f9yqMiE9
And here is when I try to add the docttirne configuration: http://pastebin.com/Nq6yWQDg

What can I do to solve that?

**Comment by x86demon** [comment]
Hi, @jbarberillo 
How did you added doctrine-extensions to your project? Please check your autoloading

**Comment by jbarberillo** [comment]
I put the downloaded folder to the symfony project in the vendor folder
Here is the route of the doctrine-extensions.
![seleccion_003](https://cloud.githubusercontent.com/assets/8222977/13075676/417a34ec-d4ad-11e5-8ec3-cf9866edf245.jpg)
Here is my app/autoload.php: http://pastebin.com/nDJEeQdu
Thanks for answer

**Comment by x86demon** [comment]
Just add dependency to your composer.json and run composer update instead.

**Comment by hacfi** [comment]
@jbarberillo Enter the following in your terminal in the project root: 

```
rm -rf vendor/oro/doctrine-extensions
composer require oro/doctrine-extensions:"dev-master"
```

This will download the package and add it to composer’s autoloading.

**Comment by jbarberillo** [comment]
Thank you it works
