### ISSUE TITLE
FROM_UNIXTIME SQL method

### ISSUE THREAD

**Issue by bjunc** [orocrm/doctrine-extensions#21]
I needed this function, and quickly created it myself by using the `SimpleFunction` convention (same as `YEAR`, `TIME`, `DATE`, etc.).

Worked great, and super simple.  Any reason this wasn't added before?

**Comment by x86demon** [comment]
Hi, @bjunc 
You may create PR with your implementation
Please, not that it should be compatible with MySQL and PostgreSQL and covered with tests.
