### ISSUE TITLE
WEEK with mode selector

### ISSUE THREAD

**Issue by lsv** [orocrm/doctrine-extensions#23]
As week numbers starts different from country to country - mysql have added a "mode" selector to week.

https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_week

You have hardcoded to 3 in both mysql and postgresql - would it be possible to change this value, so I could write ```WEEK(xxx, 1)``` in my dql - Right now I just get a ```"[Syntax Error] line 0, col 65: Error: Expected Doctrine\\ORM\\Query\\Lexer::T_CLOSE_PARENTHESIS, got ','"```

**Comment by x86demon** [comment]
Hi, @lsv 
doctrine-extensions provide additional functions and compatibility layer for MySQL and PostgreSQL. Same functions return same results on different platforms.
According to ISO

> The number of the ISO 8601 week-numbering week of the year. By definition, ISO weeks start on Mondays and the first week of a year contains January 4 of that year. In other words, the first Thursday of a year is in week 1 of that year.

In the ISO week-numbering system, it is possible for early-January dates to be part of the 52nd or 53rd week of the previous year, and for late-December dates to be part of the first week of the next year. For example, 2005-01-01 is part of the 53rd week of year 2004, and 2006-01-01 is part of the 52nd week of year 2005, while 2012-12-31 is part of the first week of 2013. It's recommended to use the isoyear field together with week to get consistent results.
